---
title: "Data Cleaning"
author: "Albert Chow"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

<h3>
Load Data
</h3>
```{r}
ast_data <- read.table("../Data/Linelist SENTRY site_136.csv", header=TRUE, skipNul =TRUE, sep=",", na.strings = c(""))
```
<hr>
<br></br>
<h3>
Filtering EC data
</h3>
```{r}
# Selects for EC while dropping all na columns

ast_ecoli <- ast_data %>% 
  filter(.[, 11] == "EC") %>% 
  select(which(colSums(!is.na(.)) > 0)) %>% 
  select(c(1, 4, 11, 17:57))
  
# Separate UTI data
ast_ec_uti <- ast_ecoli %>% 
  filter(.[, 4] == "urinary tract infection")

#save(ast_ec_uti, file = "../Data/ast_ecoli.RData")
ast_ecoli <- ast_ecoli %>% 
  filter(.[, 4]  != "urinary tract infection")

# Save working DF
# save(ast_ecoli, file = "../Data/ast_ecoli.RData")

# make csv of drugs that was tested
drg_tested <- ast_ecoli %>% 
  select_if(colSums(!is.na(.)) > 0) %>% 
  select(c(5:length(.)))

drg_tested_names <- as.data.frame(names(drg_tested))
# write_csv(drg_tested_names, "../Data/ec_bp_new.csv")
```
<hr>
<br></br>
<h3>
Casey's code to tabulate data
</h3>
```{r}
# function to summarize percent of isolates with missing MIC
pct_missing <- function (x){
  round(sum(is.na(x)) / length(x), 2)
}

#tabulate the percent of missing data for each anti-microbials by study year

ec_tab <- ast_ecoli %>% 
  select(c(2, 5:length(.))) %>% 
  group_by(.[, 1]) %>% 
  summarise(across(2:(length(.) - 1), pct_missing))

# drugs questionable at least tested in 5 years
drugs <- ec_tab %>% 
  select(-c(1)) %>% 
  summarise(across(.cols = everything(), sum)) %>% 
  select(which(. <= 0))

am_included <- names(drugs)

# Table of AST data with drugs that was tested for more than 5 years
ast_ecoli_cleaned <- ast_ecoli %>% 
  select(c(1, 4), all_of(am_included))
### save(ast_ecoli_cleaned, file = "../Data/ast_ecoli_cleaned.RData")

# vector name of drugs tested for filtering if needed
ast_ec_omit <- ast_ecoli %>% 
  select(-all_of(am_included))

drugs_tested <- tibble(am_included)
```
<hr>
<br></br>
<h3>
Cleaning Bp data
</h3>
```{r}
bp_ec_eucast <- read.csv("../Data/ec_bp_eucast.csv")
bp_ec_clsi <- read.csv("../Data/ec_bp_clsi.csv")

#Drop am without s and r, NSbp is <=

bp_ec_eucast <- bp_ec_eucast %>% 
  filter(!is.na(.[, 4]) & !is.na(.[, 6])) %>% 
  mutate('NSbp' = as.numeric(.[, 4]))

#ECV values
bp_ec_eucast <- bp_ec_eucast %>% 
  filter(!is.na(.[, 7]) & !is.na(.[, 6])) %>% 
  mutate('NSbp' = as.numeric(.[, 7]))

write_csv(bp_ec_eucast, "../Data/bp_ec_eucast.csv")

bp_ec_clsi <- bp_ec_clsi %>% 
  filter(!is.na(.[, 4]) & !is.na(.[, 6])) %>% 
  mutate('NSbp' = as.numeric(.[, 4]))

write_csv(bp_ec_clsi, "../Data/bp_ec_clsi.csv")
```
<hr>
<br></br>
<h3>
Data Cleaning 
</h3>
```{r}
names(bp_ec_eucast)[1] <- "Antimicrobial" #CC, mic interp function references a column "Antimicrobial" with capital "A"
# numerical index for mic to interpretation function
eucast_am_bp_ind <- match(bp_ec_eucast$Antimicrobial, names(ast_ecoli_cleaned))
eucast_am_bp_ind <- eucast_am_bp_ind[!is.na(eucast_am_bp_ind)]

clsi_am_bp_ind <- match(bp_ec_clsi$Antimicrobial, names(ast_ecoli_cleaned))
clsi_am_bp_ind <- clsi_am_bp_ind[!is.na(clsi_am_bp_ind)]

source("../scripts/dataclean_fun.R", local = FALSE, echo = TRUE, spaced = TRUE)

# if not logical then no bp
ec_interp_eucast <- MIC_to_interpretation(ast_ecoli_cleaned, eucast_am_bp_ind, bp_ec_eucast) #CC use this one.
ec_interp_clsi <- MIC_to_interpretation(ast_ecoli_cleaned, clsi_am_bp_ind, bp_ec_clsi)

# drop not logical values
ec_interp_eucast <- ec_interp_eucast %>% 
  select(1:2, names(ec_interp_eucast[sapply(ec_interp_eucast, is.logical)]))

save(ast_ecoli_cleaned, file = "../Data/ec_interp_eucast.RData")

ec_interp_clsi <- ec_interp_clsi %>% 
  select(1:2, names(ec_interp_clsi[sapply(ec_interp_clsi, is.logical)]))

save(ast_ecoli_cleaned, file = "../Data/ec_interp_clsi.RData")

# ECV classes

eu_mdr_df <- ec_interp_eucast %>% 
  mutate(
    BL = if_else(
       (Ampicillin.sulbactam | Piperacillin.tazobactam) == TRUE, TRUE, FALSE
     ),
    CS = if_else(
       (Cefepime | Ceftazidime | Ceftriaxone) == TRUE, TRUE, FALSE
     ),
     CP = if_else(
       (Doripenem | Imipenem | Meropenem) == TRUE, TRUE, FALSE
     )
   ) %>%
  mutate(
    mdr = rowSums(across(c(4, 9, 11, 14:18)) == TRUE, na.rm = TRUE),
    mdro = if_else(mdr >= 3, TRUE, FALSE)
  )
  
clsi_mdr_df <- ec_interp_clsi %>% 
  mutate(
    BL = if_else(
       (Ampicillin.sulbactam | Piperacillin.tazobactam) == TRUE, TRUE, FALSE
     ),
    CS = if_else(
       (Cefepime | Ceftazidime | Ceftriaxone) == TRUE, TRUE, FALSE
     ),
    CP = if_else(
       (Doripenem | Imipenem | Meropenem) == TRUE, TRUE, FALSE
     )
  ) %>%
  mutate(
    mdr = rowSums(across(c(4, 8:10, 12, 14:18)) == TRUE, na.rm = TRUE),
    mdro = if_else(mdr >= 3, TRUE, FALSE)
  )


```

<hr>
<br></br>
<h3>
Some descriptive stats
</h3>
```{r}
 # Counts of isolates by study year

ast_ecoli %>% 
  group_by(Infection.Type, Study.Year) %>% 
  summarise(N = n())


# Count of isolates by infection type
ast_ecoli_cleaned %>% 
  group_by(Infection.Type) %>% 
  summarise(N = n())

# check logical table

  
  

```
Make tables
```{r}
eu_prevalence_data <- eu_mdr_df %>% 
  select(2:15, 20) %>% 
  group_by(Infection.Type) %>% 
  summarize(
    N = n(),
    SAM = fun_sum_ab(Ampicillin.sulbactam),
    AZT = fun_sum_ab(Aztreonam),
    CEP = fun_sum_ab(Cefepime),
    CAZ = fun_sum_ab(Ceftazidime),
    CRO = fun_sum_ab(Ceftriaxone),
    DOR = fun_sum_ab(Doripenem),
    GM = fun_sum_ab(Gentamicin),
    IMI = fun_sum_ab(Imipenem),
    LVX = fun_sum_ab(Levofloxacin),
    MEM = fun_sum_ab(Meropenem),
    TZP = fun_sum_ab(Piperacillin.tazobactam),
    TGC = fun_sum_ab(Tigecycline),
    SXT = fun_sum_ab(Trimethoprim.sulfamethoxazole),
    MDR = 1 - fun_sum_ab(mdro)
  )

eu_prevalence_data_total <- eu_mdr_df %>% 
  select(2:15, 20) %>% 
  summarize(
    N = n(),
    SAM = fun_sum_ab(Ampicillin.sulbactam),
    AZT = fun_sum_ab(Aztreonam),
    CEP = fun_sum_ab(Cefepime),
    CAZ = fun_sum_ab(Ceftazidime),
    CRO = fun_sum_ab(Ceftriaxone),
    DOR = fun_sum_ab(Doripenem),
    GM = fun_sum_ab(Gentamicin),
    IMI = fun_sum_ab(Imipenem),
    LVX = fun_sum_ab(Levofloxacin),
    MEM = fun_sum_ab(Meropenem),
    TZP = fun_sum_ab(Piperacillin.tazobactam),
    TGC = fun_sum_ab(Tigecycline),
    SXT = fun_sum_ab(Trimethoprim.sulfamethoxazole),
    MDR = 1 - fun_sum_ab(mdro)
  )
write_csv(eu_prevalence_data, "../Data/eu_prevalence_data.csv")

clsi_prevalence_data <- clsi_mdr_df %>% 
  select(2:15, 20) %>% 
  group_by(Infection.Type) %>% 
  summarize(
    N = n(),
    SAM = fun_sum_ab(Ampicillin.sulbactam),
    AZT = fun_sum_ab(Aztreonam),
    CEP = fun_sum_ab(Cefepime),
    CAZ = fun_sum_ab(Ceftazidime),
    CRO = fun_sum_ab(Ceftriaxone),
    DOR = fun_sum_ab(Doripenem),
    GM = fun_sum_ab(Gentamicin),
    IMI = fun_sum_ab(Imipenem),
    LVX = fun_sum_ab(Levofloxacin),
    MEM = fun_sum_ab(Meropenem),
    TZP = fun_sum_ab(Piperacillin.tazobactam),
    DOX = fun_sum_ab(Doxycycline),
    SXT = fun_sum_ab(Trimethoprim.sulfamethoxazole),
    MDR = 1 - fun_sum_ab(mdro)
  )

clsi_prevalence_data_total <- clsi_mdr_df %>% 
  select(2:15, 20) %>% 
  
  summarize(
    N = n(),
    SAM = fun_sum_ab(Ampicillin.sulbactam),
    AZT = fun_sum_ab(Aztreonam),
    CEP = fun_sum_ab(Cefepime),
    CAZ = fun_sum_ab(Ceftazidime),
    CRO = fun_sum_ab(Ceftriaxone),
    DOR = fun_sum_ab(Doripenem),
    GM = fun_sum_ab(Gentamicin),
    IMI = fun_sum_ab(Imipenem),
    LVX = fun_sum_ab(Levofloxacin),
    MEM = fun_sum_ab(Meropenem),
    TZP = fun_sum_ab(Piperacillin.tazobactam),
    DOX = fun_sum_ab(Doxycycline),
    SXT = fun_sum_ab(Trimethoprim.sulfamethoxazole),
    MDR = 1 - fun_sum_ab(mdro)
  )

write_csv(clsi_prevalence_data, "../Data/clsi_prevalence_data.csv")

save(eu_prevalence_data, file = "../Data/eu_prevalance.RData")
save(clsi_prevalence_data, file = "../Data/clsi_prevalance.RData")

```
Data Splitting
```{r}

inf_type_split <- split(eu_mdr_df, eu_mdr_df$Infection.Type)
inf_type_split_clsi <- split(clsi_mdr_df, clsi_mdr_df$Infection.Type)

eu_abx_names <- eu_mdr_df %>% 
  select(3:15) %>% 
  names()

clsi_abx_names <- clsi_mdr_df %>% 
  select(3:15) %>% 
  names()

#### eu split  
eu_bld_db <- as.data.frame(inf_type_split[1]) %>% 
  select(3:15) %>% 
  setNames(eu_abx_names)

eu_inab_db <- as.data.frame(inf_type_split[2]) %>% 
  select(3:15) %>% 
  setNames(eu_abx_names)

eu_pneu_db <- as.data.frame(inf_type_split[3]) %>% 
  select(3:15) %>% 
  setNames(eu_abx_names)

eu_skin_db <- as.data.frame(inf_type_split[4]) %>% 
  select(3:15) %>% 
  setNames(eu_abx_names)

eu_all_db <- eu_mdr_df %>% 
  select(3:15) %>% 
  setNames(eu_abx_names)

# Inspect for data for NA select only one with less than 25% missing

fun_remove <- function(df){
  rm_names <- df %>% 
    summarise(across(everything(),
                   pct_missing)) %>%
  select(which(. <= 0.25))
  
  rm_names <- names(rm_names)
  
  df <- df %>% 
    select(all_of(rm_names))
  
  return(df)
}



test_fun <- fun_remove(eu_all_db)

#### clsi split

clsi_bld_db <- as.data.frame(inf_type_split_clsi[1]) %>% 
  select(3:15) %>% 
  setNames(clsi_abx_names)

clsi_inab_db <- as.data.frame(inf_type_split_clsi[2]) %>% 
  select(3:15) %>% 
  setNames(clsi_abx_names)

clsi_pneu_db <- as.data.frame(inf_type_split_clsi[3]) %>% 
  select(3:15) %>% 
  setNames(clsi_abx_names)

clsi_skin_db <- as.data.frame(inf_type_split_clsi[4]) %>% 
  select(3:15) %>% 
  setNames(clsi_abx_names)

clsi_all_db <- clsi_mdr_df %>% 
  select(3:15) %>% 
  setNames(clsi_abx_names)

```







Data Check
```{r}
###### Eucast data
eu_ab <- ec_interp_eucast %>% 
  select(1, 3:length(.))

eu_ab_names <- names(eu_ab)

ab_ecoli <- ast_ecoli_cleaned %>%
  select(c(1, eu_ab_names))

eu_check <- full_join(ab_ecoli, eu_ab, by = "Collection.Number")

eu_check <- eu_check[, c(1, 
                         2, 16, 
                         3, 17, 
                         4, 18, 
                         5, 19, 
                         6, 20, 
                         7, 21, 
                         8, 22, 
                         9, 23, 
                         10, 24,
                         11, 25,
                         12, 26,
                         13, 27,
                         14, 28,
                         15, 29)]

# eu ab with bp
bp_ec_eucast %>% 
  filter(Antimicrobial %in% eu_ab_names) %>% 
  select(c(1, 8))

######## clsi data

clsi_ab <- ec_interp_clsi %>% 
  select(1, 3:length(.))

clsi_ab_names <- names(clsi_ab)

ab_ecoli_clsi <- ast_ecoli_cleaned %>% 
  select(c(1, clsi_ab_names))

clsi_check <- full_join(ab_ecoli_clsi, clsi_ab, by = "Collection.Number")

clsi_check <- clsi_check[, c(1,
                             2, 15,
                             3, 16,
                             4, 17,
                             5, 18,
                             6, 19,
                             7, 20,
                             8, 21,
                             9, 22,
                             10, 23,
                             11, 24,
                             12, 25,
                             13, 26,
                             14, 27)]

bp_ec_clsi %>% 
  filter(Antimicrobial %in% clsi_ab_names) %>% 
  select(c(1, 8))

```
Functions to abv names
```{r}

test_df <- mined_clsi_all_set

test_df2 <- test_df %>% 
  mutate(across(all.sets.items, as.character)) %>%
  select(2) %>% 
  separate(all.sets.items, into = paste0("node", 1:4), sep = ",")


test_df2 <- data.frame(lapply(test_df2,
                       function(x) {
                         gsub("[\\{ | \\}]", "", x)
                       }))


test_df2$node1 <- bp_ec_clsi[match(test_df2$node1, bp_ec_clsi$Antimicrobial), ]$abbreviation
test_df2$node2 <- bp_ec_clsi[match(test_df2$node2, bp_ec_clsi$Antimicrobial), ]$abbreviation
test_df2$node3 <- bp_ec_clsi[match(test_df2$node3, bp_ec_clsi$Antimicrobial), ]$abbreviation
test_df2$node4 <- bp_ec_clsi[match(test_df2$node4, bp_ec_clsi$Antimicrobial), ]$abbreviation

test_df2 <- test_df2 %>% 
  unite(node1:node4, col = "combo", sep = ".", remove = FALSE, na.rm = TRUE) %>% 
  select(combo)

test_df$combo <- test_df2$combo



```

