---
title: "mining sets"
author: "Albert Chow"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arulesViz)
```

Model Iteration
```{r}
# find indexes of antimicrobial column in df, ecv and clsi data is the same
am_col <- eu_mdr_df %>% 
  select(1:15) 
am_col <- match(names(am_col)[sapply(am_col, is.logical)], names(am_col))


# All infection types transactions
eu_all_types <- as(eu_all_db, "transactions")

# eu_all_types
# 1. Minimum support
min_sup <- 1 / length(eu_all_types)
sets <- apriori(eu_all_types, parameter = list(support = min_sup,
                                               maxlen = length(am_col),
                                               minlen = 2,
                                               target = "frequent itemsets"))
## 2. Quality measures
itemset_list <- LIST(items(sets), decode = FALSE)
CrossSupRatio <- interestMeasure(sets, "crossSupportRatio", eu_all_types, reuse = TRUE)
lift <- interestMeasure(sets, "lift", eu_all_types, reuse = TRUE)

```

Iteration for all sets
```{r}
# find indexes of antimicrobial column in df, ecv and clsi data is the same
am_col <- eu_mdr_df %>% 
  select(1:15) 
am_col <- match(names(am_col)[sapply(am_col, is.logical)], names(am_col))

# eu sets
eu_db_sets <- c("eu_all_db", "eu_bld_db", "eu_inab_db", "eu_pneu_db", "eu_skin_db")

# create eu transaction databases
for (i in seq_along(eu_db_sets)) {
  x <- as(get(eu_db_sets[i]), "transactions")
  label <- paste(as.character(paste(eu_db_sets[i], "_trans", sep = "")))
  assign(label, x)
  rm(label, x)
}

# Mine sets
eu_trans_names <- c("eu_all_db_trans", "eu_bld_db_trans", "eu_inab_db_trans", "eu_pneu_db_trans", "eu_skin_db_trans")
eu_set_names <- c("eu_all_set", "eu_bld_set", "eu_inab_set", "eu_pneu_set", "eu_skin_set")
for (i in seq_along(eu_trans_names)) {
  data <- get(eu_trans_names[i])
  # minimum support
  min_sup <- 1 / length(data)
  sets <- apriori(data,
                  parameter = list(support = min_sup,
                                   maxlen = 11,
                                   minlen = 2,
                                   target = "frequent itemsets"))
  # Quality Measures
  CrossSupRatio <- interestMeasure(sets,
                                   "crossSupportRatio",
                                   data,
                                   reuse = TRUE)
  
  sets@quality$CrossSupRatio <- CrossSupRatio
  
  lift <- interestMeasure(sets,
                          "lift",
                          data,
                          reuse = TRUE)
  
  sets@quality$lift <- lift
  
  # save
  assign(eu_set_names[i], sets)
  rm(data, min_sup, sets, CrossSupRatio, lift)
}
```

```{r}
# clsi sets
clsi_db_sets <- c("clsi_all_db", "clsi_bld_db", "clsi_inab_db", "clsi_pneu_db", "clsi_skin_db")

# create clsi transaction databases
for (i in seq_along(clsi_db_sets)) {
  x <- as(get(clsi_db_sets[i]), "transactions")
  label <- paste(as.character(paste(clsi_db_sets[i], "_trans", sep = "")))
  assign(label, x)
  rm(label, x)
}

# Mine sets
clsi_trans_names <- c("clsi_all_db_trans", "clsi_bld_db_trans", "clsi_inab_db_trans", "clsi_pneu_db_trans", "clsi_skin_db_trans")
clsi_set_names <- c("clsi_all_set", "clsi_bld_set", "clsi_inab_set", "clsi_pneu_set", "clsi_skin_set")
for (i in seq_along(clsi_trans_names)) {
  data <- get(clsi_trans_names[i])
  # minimum support
  min_sup <- 1 / length(data)
  sets <- apriori(data,
                  parameter = list(support = min_sup,
                                   maxlen = 13,
                                   minlen = 2,
                                   target = "frequent itemsets"))
  # Quality Measures
  CrossSupRatio <- interestMeasure(sets,
                                   "crossSupportRatio",
                                   data,
                                   reuse = TRUE)
  
  sets@quality$CrossSupRatio <- CrossSupRatio
  
  lift <- interestMeasure(sets,
                          "lift",
                          data,
                          reuse = TRUE)
  
  sets@quality$lift <- lift
  
  # save
  assign(clsi_set_names[i], sets)
  rm(data, min_sup, sets, CrossSupRatio, lift)
}
```
Casey's code to convert to DF
```{r}
all_sets <- function (best_setNames, labelNames){
  #required packages
  require(tidyr)
  require(stringr)
  
  #first, sets must be transformed from class itemsets to data frame. uses setsAsDataFrame function
  setsAsDataFrame <- function(sets, cat) {
    itemsets <- labels(items(sets)) #itemset names
  
    #create dataframe with category and relevant quality measures
    data.frame(
      Category <- rep(cat, length(sets)),
      items <- itemsets,
      support <- quality(sets)$support,
      count <- quality(sets)$count,
      csr <- quality(sets)$CrossSupRatio,
      lift<-quality(sets)$lift
   )
  }
  
  
  #for storing itemsets
  all.sets <- data.frame()
  
  #turn each itemset database into dataframe and label with dataset name, then combine with other itemset dataframes
  for (i in seq_along(best_setNames)){ 
    dat <- get(best_setNames[i])
    cat <- labelNames[i] #labels for each dataset
    all.sets <- rbind(all.sets, setsAsDataFrame(dat, cat))
  }
  #appropriate column names
  colnames(all.sets) <- c("Category", "items", "support", "count", "csr", "lift")

  #calculate the itemset order (number of AM in the set)
  all.sets$order <- str_count(all.sets$items, ",")+1 #in the itemset string, AM are divided by ",": count the commas and add 1 for the order

  #tabulate quality measures for each itemset in each database; display with each unique itemset as a row and the QM value in each category as the columns
  all.sets.sup <- select(all.sets, "Category", "items", "support", "order") #support in each itemset. drop other QM columns
  all.sets.sup <- spread(all.sets.sup, Category, support, drop=TRUE) #create one column for each category, place support of itemset, within category, in those columns. reduces to one row per itemset
  
  #repeat for other QM
  
  all.sets.csr <- select(all.sets, "Category", "items", "csr", "order") #csr in each itemset
  all.sets.csr <- spread(all.sets.csr, Category, csr, drop=TRUE)

  all.sets.lift <- select(all.sets, "Category", "items", "lift", "order") #lift in each itemset
  all.sets.lift <- spread(all.sets.lift, Category, lift, drop=TRUE)
  
  #save all dataframes in a list
  all.sets.out <- list(all.sets, all.sets.sup, all.sets.csr, all.sets.lift) #put all results into a list
  
  names(all.sets.out) <- c("all.sets", "all.sets.sup", "all.sets.csr", "all.sets.lift")
  
  all.sets.out #return the list of dataframes
}
```
Convert to DF
```{r}
all_mine_df <- c("eu_all_set", "eu_bld_set", "eu_inab_set", "eu_pneu_set", "eu_skin_set",
                 "clsi_all_set", "clsi_bld_set", "clsi_inab_set", "clsi_pneu_set", "clsi_skin_set")

df_labels <- c("eu_all_inf", "eu_bld_inf", "eu_inab_inf", "eu_pneumo_inf", "eu_skin_tissue_inf",
               "clsi_all_set", "clsi_bld_inf", "clsi_inab_inf", "clsi_pneumo_inf", "clsi_skin_tissue_inf")

all_df <- all_sets(all_mine_df, df_labels)

split_labels <- c("df_category", "df_support", "df_csr", "df_lift")
for (i in seq_along(all_df)) {
  x <- as.data.frame(all_df[i])
  label <- paste0(as.character(split_labels[i]))
  assign(label, x)
  rm(label, x)
}
```
inspecting data for graphs
```{r}
all_mine_df <- c("eu_all_set", "eu_bld_set", "eu_inab_set", "eu_pneu_set", "eu_skin_set",
                 "clsi_all_set", "clsi_bld_set", "clsi_inab_set", "clsi_pneu_set", "clsi_skin_set")

plt_labels <- c("eu_all_plt", "eu_bld_plt", "eu_inab_plt", "eu_pneumo_plt", "eu_skin_tissue_plt",
               "clsi_all_plt", "clsi_bld_plt", "clsi_inab_plt", "clsi_pneumo_plt", "clsi_skin_tissue_plt")

for (i in seq_along(all_mine_df)) {
  data <- get(all_mine_df[i])
  x <- subset(data, subset = CrossSupRatio > 0.75)
  label <- paste0(as.character(plt_labels[i]))
  assign(label, x)
  rm(label, x, data)
  
  data <- get(plt_labels[i])
  saveAsGraph(data, paste0("../Data/graphs/", as.character(plt_labels[i]), ".graphml"))
}

#####
saveAsGraph(clsi_all_plt, "../Data/graphs/clsi_all_plt.graphml")

plot(graph_example, method = "graph")
interest_sub <- subset(eu_all_set, subset = CrossSupRatio > 0.75)
clsi_bld_plt <- subset(clsi_bld_set, subset = CrossSupRatio > 0.75)

graph_example <- head(interest_sub, n = 100, by = "lift")


saveAsGraph(head(interest_sub, n = 1000, by = "lift"), file = "clsi_all.graphml")


plot(interest_sub, method = "graph")
plot(interest_sub, measure = c("support", "lift"), shading = "CrossSupRatio")
arulesViz::plot(interest_sub, measure = "lift", method = "matrix")

### 
clsi_all_set <- subset(clsi_all_set, subset = CrossSupRatio > 0.75)
plot(clsi_all_set, method = "graph")

clsi_bld_plt <- subset(clsi_bld_set, subset = CrossSupRatio > 0.75)
plot(clsi_bld_plt, method = "graph")

clsi_inab_plt <- subset(clsi_inab_set, subset = CrossSupRatio > 0.75)
plot(clsi_inab_plt, method = "graph")

clsi_pneu_plt <- subset(clsi_inab_set, subset = CrossSupRatio > 0.75)
plot(clsi_pneu_plt, method = "graph")

clsi_skin_plt <- subset(clsi_skin_set, subset = CrossSupRatio > 0.75)
plot(clsi_skin_plt, method = "graph")
```
ecv
```{r}
eu_all_plt <- subset(eu_all_set, subset = CrossSupRatio > 0.75)
plot(eu_all_plt, method= "graph")
```
Inspecting mined sets
```{r}
# convert all set items to factors
df_category <- df_category %>% 
  mutate(across(all.sets.items, as.factor)) 

df_category_names <- df_category %>% 
  distinct(all.sets.Category)

df_category_names <- as.vector(df_category_names[, 1])

for (i in seq_along(df_category_names)) {
  label_name <- paste0("mined_", as.character(df_category_names[i]))
  x <- df_category %>% 
    filter(all.sets.Category == paste0(as.character(df_category_names[i])),
           .$all.sets.csr > 0.75) %>% 
    arrange(desc(all.sets.count))
  assign(label_name, x)
  rm(x, label_name)
}

# all sets above threshold of CSR 0.75
clsi_mined <- df_category %>% 
  filter(str_detect(.$all.sets.Category, "clsi_all"),
         .$all.sets.csr > 0.75) %>% 
  arrange(desc(all.sets.count))

  
eu_mined <- df_category %>% 
  filter(str_detect(.$all.sets.Category, "eu_all"),
         .$all.sets.csr > 0.75) %>% 
  arrange(desc(all.sets.count))

```
Combos for graphs
```{r}

fun_combo <- function(df) {
  df <- df %>%
    mutate(across(all.sets.items, as.character)) %>%
    select(2) %>% 
    separate(all.sets.items, into = paste0("node", 1:4), sep = ",")
  
  df <- data.frame(lapply(df,
                       function(x) {
                         gsub("[\\{ | \\}]", "", x)
                       }))
  df$node1 <- bp_ec_clsi[match(df$node1, bp_ec_clsi$Antimicrobial), ]$abbreviation
  df$node2 <- bp_ec_clsi[match(df$node2, bp_ec_clsi$Antimicrobial), ]$abbreviation
  df$node3 <- bp_ec_clsi[match(df$node3, bp_ec_clsi$Antimicrobial), ]$abbreviation
  df$node4 <- bp_ec_clsi[match(df$node4, bp_ec_clsi$Antimicrobial), ]$abbreviation
  
  df <- df %>%
    unite(node1:node4, col = "combo", sep = ".", remove = FALSE, na.rm = TRUE) %>%
    select(combo)
  
  df
}

combo_clsi_bld <- fun_combo(mined_clsi_bld_inf)
write_csv(combo_clsi_all, "../Data/combo_clsi_bld.csv")

combo_clsi_all <- fun_combo(mined_clsi_all_set)
write_csv(combo_clsi_all, "../Data/combo_clsi_all.csv")
```



